/*
 * NOTICES
 * -------
 *
 * Copyright 2026 by Gatekeeper Systems All Rights Reserved.
 *
 * Unpublished Work -- Protected under the copyright laws of the United States.
 *
 * Restricted Rights Legend: Use, duplication or disclosure of the software
 * contained hereon is governed by the terms of a license agreement.  In
 * the absence of an agreement, use, duplication or disclosure by the United
 * States Government is subject to restrictions stated in subparagraph
 * (c)(1) of the Commercial Computer Software -- Restricted Rights clause
 * at FAR 52.227-9 or subparagraph (c)(1)(ii) of the Rights in Technical
 * Data and Computer Software clause at DFARS 252.227-7013, as applicable.
 *
 * Contractor/Manufacturer:
 *
 *     Gatekeeper Systems
 *     1010 E. Union St.
 *     Pasadena, CA 91106
 *
 *     Tel: (626) 449-3070 or (800) 424-3070
 *     Fax: (626) 440-1742
 *
 *     E-Mail: info@gatekeeper.com
 *     URL:    http://www.gatekeeper.com
 *
 * Generated by scaffold version 4.0.1-SNAPSHOT rb1df1f95d84beef5f7b22947b69311d59e90d0c6
 */
package gks.clark.inspections.model;


/*
 ==========================================================================
 AUTO GENERATED FILE! - Do not edit, as your changes will be overwritten
 ==========================================================================
*/
public class CriteriaSiteFilter implements gks.clark.inspections.SiteFilter {
    /*
     ==========================================================================
     Fields
     ==========================================================================
    */
    String circuit;
    gks.clark.inspections.AssetTypeFilter[] types = gks.clark.inspections.AssetTypeFilter.values();

    /*
     ==========================================================================
     Constructors
     ==========================================================================
    */
    public CriteriaSiteFilter() {
    }

    /*
     ==========================================================================
     Getter and setters
     ==========================================================================
    */
    public void setCircuit(String circuit) {
        this.circuit = circuit;
    }

    public String getCircuit() {
        return circuit;
    }

    public void setTypes(gks.clark.inspections.AssetTypeFilter[] types) {
        this.types = types;
    }

    public gks.clark.inspections.AssetTypeFilter[] getTypes() {
        return types;
    }
}
