/*
 * NOTICES
 * -------
 *
 * Copyright 2026 by Gatekeeper Systems All Rights Reserved.
 *
 * Unpublished Work -- Protected under the copyright laws of the United States.
 *
 * Restricted Rights Legend: Use, duplication or disclosure of the software
 * contained hereon is governed by the terms of a license agreement.  In
 * the absence of an agreement, use, duplication or disclosure by the United
 * States Government is subject to restrictions stated in subparagraph
 * (c)(1) of the Commercial Computer Software -- Restricted Rights clause
 * at FAR 52.227-9 or subparagraph (c)(1)(ii) of the Rights in Technical
 * Data and Computer Software clause at DFARS 252.227-7013, as applicable.
 *
 * Contractor/Manufacturer:
 *
 *     Gatekeeper Systems
 *     1010 E. Union St.
 *     Pasadena, CA 91106
 *
 *     Tel: (626) 449-3070 or (800) 424-3070
 *     Fax: (626) 440-1742
 *
 *     E-Mail: info@gatekeeper.com
 *     URL:    http://www.gatekeeper.com
 *
 * Generated by scaffold version 4.0.1-SNAPSHOT rb1df1f95d84beef5f7b22947b69311d59e90d0c6
 */
package gks.clark.inspections.model;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.stream.Collectors;

/*
 ==========================================================================
 AUTO GENERATED FILE! - Do not edit, as your changes will be overwritten
 ==========================================================================
*/
public class GlobalidSiteFilter implements gks.clark.inspections.SiteFilter {
    /*
     ==========================================================================
     Fields
     ==========================================================================
    */
    String idString;

    /*
     ==========================================================================
     Constructors
     ==========================================================================
    */
    public GlobalidSiteFilter() {
    }

    /*
     ==========================================================================
     Getter and setters
     ==========================================================================
    */
    public void setIdString(String idString) {
        this.idString = idString;
    }

    public String getIdString() {
        return idString;
    }

    public List<String> getNormalizedIds() {
        if (idString == null || idString.trim().isEmpty()) return Collections.emptyList();
        return Arrays.stream(idString.trim().split("\\s+"))
            .map(s -> s.replaceAll("[{}\\-]", "").toUpperCase())
            .filter(s -> s.length() == 32)
            .map(s -> "{" + s.substring(0,8) + "-" + s.substring(8,12) + "-"
                          + s.substring(12,16) + "-" + s.substring(16,20) + "-"
                          + s.substring(20) + "}")
            .collect(Collectors.toList());
    }
}
