/*
 * NOTICES
 * -------
 *
 * Copyright 2026 by Gatekeeper Systems All Rights Reserved.
 *
 * Unpublished Work -- Protected under the copyright laws of the United States.
 *
 * Restricted Rights Legend: Use, duplication or disclosure of the software
 * contained hereon is governed by the terms of a license agreement.  In
 * the absence of an agreement, use, duplication or disclosure by the United
 * States Government is subject to restrictions stated in subparagraph
 * (c)(1) of the Commercial Computer Software -- Restricted Rights clause
 * at FAR 52.227-9 or subparagraph (c)(1)(ii) of the Rights in Technical
 * Data and Computer Software clause at DFARS 252.227-7013, as applicable.
 *
 * Contractor/Manufacturer:
 *
 *     Gatekeeper Systems
 *     1010 E. Union St.
 *     Pasadena, CA 91106
 *
 *     Tel: (626) 449-3070 or (800) 424-3070
 *     Fax: (626) 440-1742
 *
 *     E-Mail: info@gatekeeper.com
 *     URL:    http://www.gatekeeper.com
 *
 * Generated by scaffold version 3.4.0
 */
package gks.clark.inspections.model;


/**
 * TableModel implementation for {@link gks.clark.inspections.model.Inspection}
 *
 * AUTO GENERATED FILE! - Do not edit, as your changes will be overwritten
 */
public class InspectionTableModel extends gks.ui.table.ArrayTableModel {
    private static final long serialVersionUID = 1L;
    public static final int KEY = 0;
    public static final int X = 1;
    public static final int Y = 2;
    public static final int TYPE = 3;
    public static final int EQUIPMENT_IDENTIFIER = 4;
    public static final int LOCATION = 5;
    public static final int COMPLETION_STATUS = 6;
    public static final int COMMENT = 7;
    public static final int COMPLETE = 8;
    public static final int MAP_KEY = 9;
    private static final String[] COLUMN_NAMES = {
            "key", "x", "y", "type", "equipmentIdentifier", "location",
            "completionStatus", "comment", "complete", "mapKey",
        };

    public String getColumnName(int column) {
        if (column < 0) {
            return super.getColumnName(column);
        }

        return COLUMN_NAMES[column];
    }

    public Class<?> getColumnClass(int column) {
        if (column < 0) {
            return super.getColumnClass(column);
        }

        switch (column) {
        case COMPLETION_STATUS:
            return gks.clark.inspections.model.CompletionStatus.class;

        case X:
        case Y:
            return Double.class;

        case COMPLETE:
            return Boolean.class;

        default:
            return String.class;
        }
    }

    public Object getValueAt(Object value, int column) {
        gks.clark.inspections.model.Inspection v = (gks.clark.inspections.model.Inspection) value;

        switch (column) {
        case KEY:
            return v.getKey();

        case X:
            return v.getX();

        case Y:
            return v.getY();

        case TYPE:
            return v.getType();

        case EQUIPMENT_IDENTIFIER:
            return v.getEquipmentIdentifier();

        case LOCATION:
            return v.getLocation();

        case COMPLETION_STATUS:
            return v.getCompletionStatus();

        case COMMENT:
            return v.getComment();

        case COMPLETE:
            return Boolean.valueOf(v.isComplete());

        case MAP_KEY:
            return v.getMapKey();

        default:
            throw new IllegalArgumentException();
        }
    }

    public int getColumnCount() {
        return 10;
    }

    protected Class<?> getValueClass() {
        return gks.clark.inspections.model.Inspection.class;
    }
}
