/*
 * NOTICES
 * -------
 *
 * Copyright 2026 by Gatekeeper Systems All Rights Reserved.
 *
 * Unpublished Work -- Protected under the copyright laws of the United States.
 *
 * Restricted Rights Legend: Use, duplication or disclosure of the software
 * contained hereon is governed by the terms of a license agreement.  In
 * the absence of an agreement, use, duplication or disclosure by the United
 * States Government is subject to restrictions stated in subparagraph
 * (c)(1) of the Commercial Computer Software -- Restricted Rights clause
 * at FAR 52.227-9 or subparagraph (c)(1)(ii) of the Rights in Technical
 * Data and Computer Software clause at DFARS 252.227-7013, as applicable.
 *
 * Contractor/Manufacturer:
 *
 *     Gatekeeper Systems
 *     1010 E. Union St.
 *     Pasadena, CA 91106
 *
 *     Tel: (626) 449-3070 or (800) 424-3070
 *     Fax: (626) 440-1742
 *
 *     E-Mail: info@gatekeeper.com
 *     URL:    http://www.gatekeeper.com
 *
 * Generated by scaffold version 3.4.0
 */
package gks.clark.inspections.model;


/*
 ==========================================================================
 AUTO GENERATED FILE! - Do not edit, as your changes will be overwritten
 ==========================================================================
*/
public class Inspection implements gks.util.dto.ServerTransferObject,
    gks.util.Mappable {
    /*
     ==========================================================================
     Fields
     ==========================================================================
    */
    String key;
    Double x;
    Double y;
    String type;
    String equipmentIdentifier;
    String location;
    gks.clark.inspections.model.CompletionStatus completionStatus;
    String comment;

    /*
     ==========================================================================
     Constructors
     ==========================================================================
    */
    public Inspection() {
    }

    /*
    ==========================================================================
    Code includes
    ==========================================================================
    */
    public gks.util.BoundingBox getExtent(gks.util.BoundingBox scratchBox) {
        return gks.map.MapControl.getExtent(x, y, scratchBox);
    }

    public boolean isMappable() {
        return gks.map.MapControl.isMappable(x, y, getMapKey());
    }

    /*
     ==========================================================================
     Getter and setters
     ==========================================================================
    */
    public String getKey() {
        return key;
    }

    public Double getX() {
        return x;
    }

    public Double getY() {
        return y;
    }

    public String getType() {
        return type;
    }

    public String getEquipmentIdentifier() {
        return equipmentIdentifier;
    }

    public String getLocation() {
        return location;
    }

    public void setCompletionStatus(
        gks.clark.inspections.model.CompletionStatus completionStatus) {
        this.completionStatus = completionStatus;
    }

    public gks.clark.inspections.model.CompletionStatus getCompletionStatus() {
        return completionStatus;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public String getComment() {
        return comment;
    }

    public String getMapKey() {
        return key;
    }

    /*
    ==========================================================================
    Server Serializable object methods
    ==========================================================================
    */
    public void parseFromStream(gks.util.dto.DataTransferInputStream stream)
        throws gks.util.dto.DataTransferException {
        this.key = stream.read();
        this.x = stream.readDouble();
        this.y = stream.readDouble();
        this.type = stream.read();
        this.equipmentIdentifier = stream.read();
        this.location = stream.read();
        this.completionStatus = stream.readCode(gks.clark.inspections.model.CompletionStatus.class);
        this.comment = stream.read();
    }

    public void serializeToStream(gks.util.dto.DataTransferOutputStream stream)
        throws gks.util.dto.DataTransferException {
        stream.write(this.key);
        stream.write(this.x);
        stream.write(this.y);
        stream.write(this.type);
        stream.write(this.equipmentIdentifier);
        stream.write(this.location);
        stream.write(this.completionStatus);
        stream.write(this.comment);
    }

    public void serializeModifiableToStream(
        gks.util.dto.DataTransferOutputStream stream)
        throws gks.util.dto.DataTransferException {
        stream.write(this.key);
        stream.write(this.completionStatus);
        stream.write(this.comment);
    }

    /**
             * Factory method for creating an ArrayTableModel which will
             * serve this class. Table created is of class gks.clark.inspections.model.InspectionTableModel
             *
             * @see gks.clark.inspections.model.InspectionTableModel
             */
    public static gks.ui.table.ArrayTableModel createTableModel() {
        return new gks.clark.inspections.model.InspectionTableModel();
    }
}
