/*
 * NOTICES
 * -------
 *
 * Copyright 2026 by Gatekeeper Systems All Rights Reserved.
 *
 * Unpublished Work -- Protected under the copyright laws of the United States.
 *
 * Restricted Rights Legend: Use, duplication or disclosure of the software
 * contained hereon is governed by the terms of a license agreement.  In
 * the absence of an agreement, use, duplication or disclosure by the United
 * States Government is subject to restrictions stated in subparagraph
 * (c)(1) of the Commercial Computer Software -- Restricted Rights clause
 * at FAR 52.227-9 or subparagraph (c)(1)(ii) of the Rights in Technical
 * Data and Computer Software clause at DFARS 252.227-7013, as applicable.
 *
 * Contractor/Manufacturer:
 *
 *     Gatekeeper Systems
 *     1010 E. Union St.
 *     Pasadena, CA 91106
 *
 *     Tel: (626) 449-3070 or (800) 424-3070
 *     Fax: (626) 440-1742
 *
 *     E-Mail: info@gatekeeper.com
 *     URL:    http://www.gatekeeper.com
 *
 * Generated by scaffold version 4.0.1-SNAPSHOT rb1df1f95d84beef5f7b22947b69311d59e90d0c6
 */
package gks.clark.inspections.model;


/**
 * TableModel implementation for {@link gks.clark.inspections.model.Inspection}
 *
 * AUTO GENERATED FILE! - Do not edit, as your changes will be overwritten
 */
public class InspectionTableModel extends gks.ui.table.ArrayTableModel {
    private static final long serialVersionUID = 1L;
    public static final int KEY = 0;
    public static final int X = 1;
    public static final int Y = 2;
    public static final int PROGRAM = 3;
    public static final int TYPE = 4;
    public static final int EQUIPMENT_IDENTIFIER = 5;
    public static final int LOCATION = 6;
    public static final int ORDER_KEY = 7;
    public static final int ORDER_SUB_KEY = 8;
    public static final int ORDER_NUMBER = 9;
    public static final int SCHEDULED_TS = 10;
    public static final int ENTRY_TS = 11;
    public static final int CUSTOMER_NAME = 12;
    public static final int RES_PHONE = 13;
    public static final int BUS_PHONE = 14;
    public static final int CALL_FIRST = 15;
    public static final int SERVICE_ACCOUNT = 16;
    public static final int SERVICE_ADDRESS = 17;
    public static final int SERVICE_CITY = 18;
    public static final int SERVICE_ZIP = 19;
    public static final int REQUEST = 20;
    public static final int REASON = 21;
    public static final int ORDER_DESC = 22;
    public static final int WORK_LOCATION = 23;
    public static final int WORK_LOCATION_DESCRIPTION = 24;
    public static final int CREATION_USER = 25;
    public static final int COMPLETION_DATE = 26;
    public static final int PRIORITY = 27;
    public static final int MATERIALS_REQUIRED = 28;
    public static final int ATTACHED_FILES = 29;
    public static final int COMPLETION_STATUS = 30;
    public static final int ISSUE_PRIORITY = 31;
    public static final int COMMENT = 32;
    public static final int RESOLUTION_STATUS = 33;
    public static final int RESOLUTION_WORK_ORDER = 34;
    public static final int RESOLUTION_COMMENT = 35;
    public static final int COMPLETE = 36;
    public static final int ATTACHED_FILE_COUNT = 37;
    public static final int MAP_KEY = 38;
    public static final int SERVICE_ADDRESS_COMPLETE = 39;
    private static final String[] COLUMN_NAMES = {
            "key", "x", "y", "program", "type", "equipmentIdentifier",
            "location", "orderKey", "orderSubKey", "orderNumber", "scheduledTs",
            "entryTs", "customerName", "resPhone", "busPhone", "callFirst",
            "serviceAccount", "serviceAddress", "serviceCity", "serviceZip",
            "request", "reason", "orderDesc", "workLocation",
            "workLocationDescription", "creationUser", "completionDate",
            "priority", "materialsRequired", "attachedFiles", "completionStatus",
            "issuePriority", "comment", "resolutionStatus",
            "resolutionWorkOrder", "resolutionComment", "complete",
            "attachedFileCount", "mapKey", "serviceAddressComplete",
        };

    public String getColumnName(int column) {
        if (column < 0) {
            return super.getColumnName(column);
        }

        return COLUMN_NAMES[column];
    }

    public Class<?> getColumnClass(int column) {
        if (column < 0) {
            return super.getColumnClass(column);
        }

        switch (column) {
        case COMPLETION_STATUS:
            return gks.clark.inspections.model.CompletionStatus.class;

        case X:
        case Y:
            return Double.class;

        case ATTACHED_FILES:
            return java.util.List.class;

        case ISSUE_PRIORITY:
            return gks.clark.inspections.model.IssuePriority.class;

        case PROGRAM:
            return gks.clark.inspections.model.Program.class;

        case RESOLUTION_STATUS:
            return gks.clark.inspections.model.ResolutionStatus.class;

        case COMPLETE:
            return Boolean.class;

        case ATTACHED_FILE_COUNT:
            return Integer.class;

        default:
            return String.class;
        }
    }

    public Object getValueAt(Object value, int column) {
        gks.clark.inspections.model.Inspection v = (gks.clark.inspections.model.Inspection) value;

        switch (column) {
        case KEY:
            return v.getKey();

        case X:
            return v.getX();

        case Y:
            return v.getY();

        case PROGRAM:
            return v.getProgram();

        case TYPE:
            return v.getType();

        case EQUIPMENT_IDENTIFIER:
            return v.getEquipmentIdentifier();

        case LOCATION:
            return v.getLocation();

        case ORDER_KEY:
            return v.getOrderKey();

        case ORDER_SUB_KEY:
            return v.getOrderSubKey();

        case ORDER_NUMBER:
            return v.getOrderNumber();

        case SCHEDULED_TS:
            return v.getScheduledTs();

        case ENTRY_TS:
            return v.getEntryTs();

        case CUSTOMER_NAME:
            return v.getCustomerName();

        case RES_PHONE:
            return v.getResPhone();

        case BUS_PHONE:
            return v.getBusPhone();

        case CALL_FIRST:
            return v.getCallFirst();

        case SERVICE_ACCOUNT:
            return v.getServiceAccount();

        case SERVICE_ADDRESS:
            return v.getServiceAddress();

        case SERVICE_CITY:
            return v.getServiceCity();

        case SERVICE_ZIP:
            return v.getServiceZip();

        case REQUEST:
            return v.getRequest();

        case REASON:
            return v.getReason();

        case ORDER_DESC:
            return v.getOrderDesc();

        case WORK_LOCATION:
            return v.getWorkLocation();

        case WORK_LOCATION_DESCRIPTION:
            return v.getWorkLocationDescription();

        case CREATION_USER:
            return v.getCreationUser();

        case COMPLETION_DATE:
            return v.getCompletionDate();

        case PRIORITY:
            return v.getPriority();

        case MATERIALS_REQUIRED:
            return v.getMaterialsRequired();

        case ATTACHED_FILES:
            return java.util.Arrays.asList(v.getAttachedFiles());

        case COMPLETION_STATUS:
            return v.getCompletionStatus();

        case ISSUE_PRIORITY:
            return v.getIssuePriority();

        case COMMENT:
            return v.getComment();

        case RESOLUTION_STATUS:
            return v.getResolutionStatus();

        case RESOLUTION_WORK_ORDER:
            return v.getResolutionWorkOrder();

        case RESOLUTION_COMMENT:
            return v.getResolutionComment();

        case COMPLETE:
            return Boolean.valueOf(v.isComplete());

        case ATTACHED_FILE_COUNT:
            return new Integer(v.getAttachedFileCount());

        case MAP_KEY:
            return v.getMapKey();

        case SERVICE_ADDRESS_COMPLETE:
            return v.getServiceAddressComplete();

        default:
            throw new IllegalArgumentException();
        }
    }

    public int getColumnCount() {
        return 40;
    }

    protected Class<?> getValueClass() {
        return gks.clark.inspections.model.Inspection.class;
    }
}
