/*
 * NOTICES
 * -------
 *
 * Copyright 2026 by Gatekeeper Systems All Rights Reserved.
 *
 * Unpublished Work -- Protected under the copyright laws of the United States.
 *
 * Restricted Rights Legend: Use, duplication or disclosure of the software
 * contained hereon is governed by the terms of a license agreement.  In
 * the absence of an agreement, use, duplication or disclosure by the United
 * States Government is subject to restrictions stated in subparagraph
 * (c)(1) of the Commercial Computer Software -- Restricted Rights clause
 * at FAR 52.227-9 or subparagraph (c)(1)(ii) of the Rights in Technical
 * Data and Computer Software clause at DFARS 252.227-7013, as applicable.
 *
 * Contractor/Manufacturer:
 *
 *     Gatekeeper Systems
 *     1010 E. Union St.
 *     Pasadena, CA 91106
 *
 *     Tel: (626) 449-3070 or (800) 424-3070
 *     Fax: (626) 440-1742
 *
 *     E-Mail: info@gatekeeper.com
 *     URL:    http://www.gatekeeper.com
 *
 * Generated by scaffold version 4.0.1-SNAPSHOT rb1df1f95d84beef5f7b22947b69311d59e90d0c6
 */
package gks.clark.inspections.model;


/*
 ==========================================================================
 AUTO GENERATED FILE! - Do not edit, as your changes will be overwritten
 ==========================================================================
*/
public class Inspection implements gks.util.dto.ServerTransferObject,
    gks.util.Mappable {
    /*
     ==========================================================================
     Fields
     ==========================================================================
    */
    String key;
    Double x;
    Double y;
    gks.clark.inspections.model.Program program;
    String type;
    String equipmentIdentifier;
    String location;
    String orderKey;
    String orderSubKey;
    String orderNumber;
    String scheduledTs;
    String entryTs;
    String customerName;
    String resPhone;
    String busPhone;
    String callFirst;
    String serviceAccount;
    String serviceAddress;
    String serviceCity;
    String serviceZip;
    String request;
    String reason;
    String orderDesc;
    String workLocation;
    String workLocationDescription;
    String creationUser;
    String completionDate;
    String priority;
    String materialsRequired;
    gks.clark.inspections.FileAttachment[] attachedFiles;
    gks.clark.inspections.model.CompletionStatus completionStatus;
    gks.clark.inspections.model.IssuePriority issuePriority;
    String comment;
    gks.clark.inspections.model.ResolutionStatus resolutionStatus;
    String resolutionWorkOrder;
    String resolutionComment;

    /*
     ==========================================================================
     Constructors
     ==========================================================================
    */
    public Inspection() {
    }

    /*
    ==========================================================================
    Code includes
    ==========================================================================
    */
    public gks.util.BoundingBox getExtent(gks.util.BoundingBox scratchBox) {
        return gks.map.MapControl.getExtent(x, y, scratchBox);
    }

    public boolean isMappable() {
        return gks.map.MapControl.isMappable(x, y, getMapKey());
    }

    /*
     ==========================================================================
     Getter and setters
     ==========================================================================
    */
    public String getKey() {
        return key;
    }

    public Double getX() {
        return x;
    }

    public Double getY() {
        return y;
    }

    public gks.clark.inspections.model.Program getProgram() {
        return program;
    }

    public String getType() {
        return type;
    }

    public String getEquipmentIdentifier() {
        return equipmentIdentifier;
    }

    public String getLocation() {
        return location;
    }

    public String getOrderKey() {
        return orderKey;
    }

    public String getOrderSubKey() {
        return orderSubKey;
    }

    public String getOrderNumber() {
        return orderNumber;
    }

    public String getScheduledTs() {
        return scheduledTs;
    }

    public String getEntryTs() {
        return entryTs;
    }

    public String getCustomerName() {
        return customerName;
    }

    public String getResPhone() {
        return resPhone;
    }

    public String getBusPhone() {
        return busPhone;
    }

    public String getCallFirst() {
        return callFirst;
    }

    public String getServiceAccount() {
        return serviceAccount;
    }

    public String getServiceAddress() {
        return serviceAddress;
    }

    public String getServiceCity() {
        return serviceCity;
    }

    public String getServiceZip() {
        return serviceZip;
    }

    public String getRequest() {
        return request;
    }

    public String getReason() {
        return reason;
    }

    public String getOrderDesc() {
        return orderDesc;
    }

    public String getWorkLocation() {
        return workLocation;
    }

    public String getWorkLocationDescription() {
        return workLocationDescription;
    }

    public String getCreationUser() {
        return creationUser;
    }

    public String getCompletionDate() {
        return completionDate;
    }

    public String getPriority() {
        return priority;
    }

    public String getMaterialsRequired() {
        return materialsRequired;
    }

    public void setAttachedFiles(
        gks.clark.inspections.FileAttachment[] attachedFiles) {
        this.attachedFiles = attachedFiles;
    }

    public gks.clark.inspections.FileAttachment[] getAttachedFiles() {
        return attachedFiles;
    }

    public void setCompletionStatus(
        gks.clark.inspections.model.CompletionStatus completionStatus) {
        this.completionStatus = completionStatus;
    }

    public gks.clark.inspections.model.CompletionStatus getCompletionStatus() {
        return completionStatus;
    }

    public void setIssuePriority(
        gks.clark.inspections.model.IssuePriority issuePriority) {
        this.issuePriority = issuePriority;
    }

    public gks.clark.inspections.model.IssuePriority getIssuePriority() {
        return issuePriority;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public String getComment() {
        return comment;
    }

    public void setResolutionStatus(
        gks.clark.inspections.model.ResolutionStatus resolutionStatus) {
        this.resolutionStatus = resolutionStatus;
    }

    public gks.clark.inspections.model.ResolutionStatus getResolutionStatus() {
        return resolutionStatus;
    }

    public void setResolutionWorkOrder(String resolutionWorkOrder) {
        this.resolutionWorkOrder = resolutionWorkOrder;
    }

    public String getResolutionWorkOrder() {
        return resolutionWorkOrder;
    }

    public void setResolutionComment(String resolutionComment) {
        this.resolutionComment = resolutionComment;
    }

    public String getResolutionComment() {
        return resolutionComment;
    }

    public boolean isComplete() {
        return completionStatus != null;
    }

    public int getAttachedFileCount() {
        return (attachedFiles != null) ? attachedFiles.length : 0;
    }

    public String getMapKey() {
        return key;
    }

    public String getServiceAddressComplete() {
        boolean hasAddress = gks.util.Utils.isNotEmpty(serviceAddress);
        boolean hasCity = gks.util.Utils.isNotEmpty(serviceCity);
        boolean hasZip = gks.util.Utils.isNotEmpty(serviceZip);
        java.util.ArrayList<String> lines = new java.util.ArrayList<String>(2);

        // line 1
        if (hasAddress) {
            lines.add(serviceAddress);
        }

        // line 2
        if (hasCity && hasZip) {
            lines.add(serviceCity + ", " + serviceZip);
        } else if (hasCity) {
            lines.add(serviceCity);
        } else if (hasZip) {
            lines.add(serviceZip);
        }

        return gks.util.Utils.join("\n", lines);
    }

    /*
    ==========================================================================
    Server Serializable object methods
    ==========================================================================
    */
    public void parseFromStream(gks.util.dto.DataTransferInputStream stream)
        throws gks.util.dto.DataTransferException {
        this.key = stream.read();
        this.x = stream.readDouble();
        this.y = stream.readDouble();
        this.program = stream.readCode(gks.clark.inspections.model.Program.class);
        this.type = stream.read();
        this.equipmentIdentifier = stream.read();
        this.location = stream.read();
        this.orderKey = stream.read();
        this.orderSubKey = stream.read();
        this.orderNumber = stream.read();
        this.scheduledTs = stream.read();
        this.entryTs = stream.read();
        this.customerName = stream.read();
        this.resPhone = stream.read();
        this.busPhone = stream.read();
        this.callFirst = stream.read();
        this.serviceAccount = stream.read();
        this.serviceAddress = stream.read();
        this.serviceCity = stream.read();
        this.serviceZip = stream.read();
        this.request = stream.read();
        this.reason = stream.read();
        this.orderDesc = stream.read();
        this.workLocation = stream.read();
        this.workLocationDescription = stream.read();
        this.creationUser = stream.read();
        this.completionDate = stream.read();
        this.priority = stream.read();
        this.materialsRequired = stream.read();

        Integer __attachedFiles_countObj = stream.readInteger();

        if (__attachedFiles_countObj != null) {
            int __attachedFiles_count = __attachedFiles_countObj.intValue();
            this.attachedFiles = new gks.clark.inspections.FileAttachment[__attachedFiles_count];

            for (int k = 0; k < __attachedFiles_count; ++k) {
                this.attachedFiles[k] = new gks.clark.inspections.FileAttachment();
                this.attachedFiles[k].parseFromStream(stream);
            }
        } else {
            this.attachedFiles = null;
        }

        this.completionStatus = stream.readCode(gks.clark.inspections.model.CompletionStatus.class);
        this.issuePriority = stream.readCode(gks.clark.inspections.model.IssuePriority.class);
        this.comment = stream.read();
        this.resolutionStatus = stream.readCode(gks.clark.inspections.model.ResolutionStatus.class);
        this.resolutionWorkOrder = stream.read();
        this.resolutionComment = stream.read();
    }

    public void serializeToStream(gks.util.dto.DataTransferOutputStream stream)
        throws gks.util.dto.DataTransferException {
        stream.write(this.key);
        stream.write(this.x);
        stream.write(this.y);
        stream.write(this.program);
        stream.write(this.type);
        stream.write(this.equipmentIdentifier);
        stream.write(this.location);
        stream.write(this.orderKey);
        stream.write(this.orderSubKey);
        stream.write(this.orderNumber);
        stream.write(this.scheduledTs);
        stream.write(this.entryTs);
        stream.write(this.customerName);
        stream.write(this.resPhone);
        stream.write(this.busPhone);
        stream.write(this.callFirst);
        stream.write(this.serviceAccount);
        stream.write(this.serviceAddress);
        stream.write(this.serviceCity);
        stream.write(this.serviceZip);
        stream.write(this.request);
        stream.write(this.reason);
        stream.write(this.orderDesc);
        stream.write(this.workLocation);
        stream.write(this.workLocationDescription);
        stream.write(this.creationUser);
        stream.write(this.completionDate);
        stream.write(this.priority);
        stream.write(this.materialsRequired);

        if (this.attachedFiles != null) {
            stream.write(this.attachedFiles.length);

            for (int k = 0; k < this.attachedFiles.length; ++k) {
                this.attachedFiles[k].serializeToStream(stream);
            }
        } else {
            stream.writeNull();
        }

        stream.write(this.completionStatus);
        stream.write(this.issuePriority);
        stream.write(this.comment);
        stream.write(this.resolutionStatus);
        stream.write(this.resolutionWorkOrder);
        stream.write(this.resolutionComment);
    }

    public void serializeModifiableToStream(
        gks.util.dto.DataTransferOutputStream stream)
        throws gks.util.dto.DataTransferException {
        stream.write(this.key);

        if (this.attachedFiles != null) {
            stream.write(this.attachedFiles.length);

            for (int k = 0; k < this.attachedFiles.length; ++k) {
                this.attachedFiles[k].serializeModifiableToStream(stream);
            }
        } else {
            stream.writeNull();
        }

        stream.write(this.completionStatus);
        stream.write(this.issuePriority);
        stream.write(this.comment);
        stream.write(this.resolutionStatus);
        stream.write(this.resolutionWorkOrder);
        stream.write(this.resolutionComment);
    }

    /**
             * Factory method for creating an ArrayTableModel which will
             * serve this class. Table created is of class gks.clark.inspections.model.InspectionTableModel
             *
             * @see gks.clark.inspections.model.InspectionTableModel
             */
    public static gks.ui.table.ArrayTableModel createTableModel() {
        return new gks.clark.inspections.model.InspectionTableModel();
    }
}
