/*
 * NOTICES
 * -------
 *
 * Copyright 2026 by Gatekeeper Systems All Rights Reserved.
 *
 * Unpublished Work -- Protected under the copyright laws of the United States.
 *
 * Restricted Rights Legend: Use, duplication or disclosure of the software
 * contained hereon is governed by the terms of a license agreement.  In
 * the absence of an agreement, use, duplication or disclosure by the United
 * States Government is subject to restrictions stated in subparagraph
 * (c)(1) of the Commercial Computer Software -- Restricted Rights clause
 * at FAR 52.227-9 or subparagraph (c)(1)(ii) of the Rights in Technical
 * Data and Computer Software clause at DFARS 252.227-7013, as applicable.
 *
 * Contractor/Manufacturer:
 *
 *     Gatekeeper Systems
 *     1010 E. Union St.
 *     Pasadena, CA 91106
 *
 *     Tel: (626) 449-3070 or (800) 424-3070
 *     Fax: (626) 440-1742
 *
 *     E-Mail: info@gatekeeper.com
 *     URL:    http://www.gatekeeper.com
 *
 * Generated by scaffold version 4.0.1-SNAPSHOT rb1df1f95d84beef5f7b22947b69311d59e90d0c6
 */
package gks.clark.inspections.model;

import gks.util.SimpleCodeCache;


/*
  ==========================================================================
  AUTO GENERATED FILE! - Do not edit, as your changes will be overwritten
  ==========================================================================
*/
public class Program extends gks.util.SimpleCode {
    private static SimpleCodeCache<Program> cache = SimpleCodeCache.create(Program.class);

    /*
    ==========================================================================
    Constructor
    ==========================================================================
    */
    public Program(String code, String description) {
        super(code, description);
    }

    /*
    ==========================================================================
    Cache methods
    ==========================================================================
    */
    public static void resetCache() {
        cache.reset();
    }

    /** Adds a new instance to the cache */
    public static Program cache(String code, String description) {
        Program __v = new Program(code, description);
        cache.cache(__v);

        return __v;
    }

    /**
     * Looks up an instance in the cache and returns it if found,
     * otherwise returns null.
     */
    public static Program lookup(String id) {
        return (Program) cache.lookup(id);
    }

    /**
     * Returns an array of all the cached instances, sorted by
     * displayString.
     */
    public static Program[] all() {
        return (Program[]) cache.all();
    }
}
