/*
 * NOTICES
 * -------
 *
 * Copyright 2026 by Gatekeeper Systems All Rights Reserved.
 *
 * Unpublished Work -- Protected under the copyright laws of the United States.
 *
 * Restricted Rights Legend: Use, duplication or disclosure of the software
 * contained hereon is governed by the terms of a license agreement.  In
 * the absence of an agreement, use, duplication or disclosure by the United
 * States Government is subject to restrictions stated in subparagraph
 * (c)(1) of the Commercial Computer Software -- Restricted Rights clause
 * at FAR 52.227-9 or subparagraph (c)(1)(ii) of the Rights in Technical
 * Data and Computer Software clause at DFARS 252.227-7013, as applicable.
 *
 * Contractor/Manufacturer:
 *
 *     Gatekeeper Systems
 *     1010 E. Union St.
 *     Pasadena, CA 91106
 *
 *     Tel: (626) 449-3070 or (800) 424-3070
 *     Fax: (626) 440-1742
 *
 *     E-Mail: info@gatekeeper.com
 *     URL:    http://www.gatekeeper.com
 *
 * Generated by scaffold version 3.4.0
 */
package gks.clark.inspections.model;


/**
 * TableModel implementation for {@link gks.clark.inspections.model.Site}
 *
 * AUTO GENERATED FILE! - Do not edit, as your changes will be overwritten
 */
public class SiteTableModel extends gks.ui.table.ArrayTableModel {
    private static final long serialVersionUID = 1L;
    public static final int YMAX = 0;
    public static final int DATA = 1;
    public static final int XMAX = 2;
    public static final int EDITABLE = 3;
    public static final int MAP_KEY = 4;
    public static final int EDITION = 5;
    public static final int COMPLETED = 6;
    public static final int YMIN = 7;
    public static final int LOCKVERSION = 8;
    public static final int VALID = 9;
    public static final int XMIN = 10;
    public static final int DISPLAY_STRING = 11;
    public static final int MODIFIABLE_DATA = 12;
    public static final int ID = 13;
    public static final int REPORT_KEY = 14;
    public static final int PERSISTENT = 15;
    public static final int CLASS = 16;
    public static final int MAPPABLE = 17;
    public static final int KEY = 18;
    public static final int CHANGED = 19;
    public static final int CLASS_TYPE = 20;
    private static final String[] COLUMN_NAMES = {
            "YMax", "data", "XMax", "editable", "mapKey", "edition", "completed",
            "YMin", "lockversion", "valid", "XMin", "displayString",
            "modifiableData", "ID", "reportKey", "persistent", "class",
            "mappable", "key", "changed", "classType",
        };

    public String getColumnName(int column) {
        if (column < 0) {
            return super.getColumnName(column);
        }

        return COLUMN_NAMES[column];
    }

    public Class<?> getColumnClass(int column) {
        if (column < 0) {
            return super.getColumnClass(column);
        }

        switch (column) {
        case CLASS:
            return Class.class;

        case DATA:
        case MODIFIABLE_DATA:
            return java.util.List.class;

        case EDITABLE:
        case COMPLETED:
        case VALID:
        case PERSISTENT:
        case MAPPABLE:
        case CHANGED:
            return Boolean.class;

        case YMAX:
        case XMAX:
        case YMIN:
        case XMIN:
            return Double.class;

        case EDITION:
        case LOCKVERSION:
            return Integer.class;

        case ID:
            return Long.class;

        default:
            return String.class;
        }
    }

    public Object getValueAt(Object value, int column) {
        gks.clark.inspections.model.Site v = (gks.clark.inspections.model.Site) value;

        switch (column) {
        case YMAX:
            return new Double(v.getYMax());

        case DATA:
            return java.util.Arrays.asList(v.getData());

        case XMAX:
            return new Double(v.getXMax());

        case EDITABLE:
            return Boolean.valueOf(v.isEditable());

        case MAP_KEY:
            return v.getMapKey();

        case EDITION:
            return new Integer(v.getEdition());

        case COMPLETED:
            return Boolean.valueOf(v.isCompleted());

        case YMIN:
            return new Double(v.getYMin());

        case LOCKVERSION:
            return new Integer(v.getLockversion());

        case VALID:
            return Boolean.valueOf(v.isValid());

        case XMIN:
            return new Double(v.getXMin());

        case DISPLAY_STRING:
            return v.getDisplayString();

        case MODIFIABLE_DATA:
            return java.util.Arrays.asList(v.getModifiableData());

        case ID:
            return new Long(v.getID());

        case REPORT_KEY:
            return v.getReportKey();

        case PERSISTENT:
            return Boolean.valueOf(v.isPersistent());

        case CLASS:
            return v.getClass();

        case MAPPABLE:
            return Boolean.valueOf(v.isMappable());

        case KEY:
            return v.getKey();

        case CHANGED:
            return Boolean.valueOf(v.isChanged());

        case CLASS_TYPE:
            return v.getClassType();

        default:
            throw new IllegalArgumentException();
        }
    }

    public int getColumnCount() {
        return 21;
    }

    protected Class<?> getValueClass() {
        return gks.clark.inspections.model.Site.class;
    }
}
