/*
 * NOTICES
 * -------
 *
 * Copyright 2026 by Gatekeeper Systems All Rights Reserved.
 *
 * Unpublished Work -- Protected under the copyright laws of the United States.
 *
 * Restricted Rights Legend: Use, duplication or disclosure of the software
 * contained hereon is governed by the terms of a license agreement.  In
 * the absence of an agreement, use, duplication or disclosure by the United
 * States Government is subject to restrictions stated in subparagraph
 * (c)(1) of the Commercial Computer Software -- Restricted Rights clause
 * at FAR 52.227-9 or subparagraph (c)(1)(ii) of the Rights in Technical
 * Data and Computer Software clause at DFARS 252.227-7013, as applicable.
 *
 * Contractor/Manufacturer:
 *
 *     Gatekeeper Systems
 *     1010 E. Union St.
 *     Pasadena, CA 91106
 *
 *     Tel: (626) 449-3070 or (800) 424-3070
 *     Fax: (626) 440-1742
 *
 *     E-Mail: info@gatekeeper.com
 *     URL:    http://www.gatekeeper.com
 *
 * Generated by scaffold version 4.0.1-SNAPSHOT rb1df1f95d84beef5f7b22947b69311d59e90d0c6
 */
package gks.clark.inspections.model;


/**
 * TableModel implementation for {@link gks.clark.inspections.model.Site}
 *
 * AUTO GENERATED FILE! - Do not edit, as your changes will be overwritten
 */
public class SiteTableModel extends gks.ui.table.ArrayTableModel {
    private static final long serialVersionUID = 1L;
    public static final int ASSET_TYPE = 0;
    public static final int ASSET_ID = 1;
    public static final int MIN_X = 2;
    public static final int MIN_Y = 3;
    public static final int MAX_X = 4;
    public static final int MAX_Y = 5;
    public static final int TYPE_DESCRIPTION = 6;
    public static final int EQUIPMENT = 7;
    public static final int LOCATION = 8;
    public static final int MAP_KEY = 9;
    public static final int KEY = 10;
    private static final String[] COLUMN_NAMES = {
            "assetType", "assetID", "minX", "minY", "maxX", "maxY",
            "typeDescription", "equipment", "location", "mapKey", "key",
        };

    public String getColumnName(int column) {
        if (column < 0) {
            return super.getColumnName(column);
        }

        return COLUMN_NAMES[column];
    }

    public Class<?> getColumnClass(int column) {
        if (column < 0) {
            return super.getColumnClass(column);
        }

        switch (column) {
        case MIN_X:
        case MIN_Y:
        case MAX_X:
        case MAX_Y:
            return Double.class;

        default:
            return String.class;
        }
    }

    public Object getValueAt(Object value, int column) {
        gks.clark.inspections.model.Site v = (gks.clark.inspections.model.Site) value;

        switch (column) {
        case ASSET_TYPE:
            return v.getAssetType();

        case ASSET_ID:
            return v.getAssetID();

        case MIN_X:
            return v.getMinX();

        case MIN_Y:
            return v.getMinY();

        case MAX_X:
            return v.getMaxX();

        case MAX_Y:
            return v.getMaxY();

        case TYPE_DESCRIPTION:
            return v.getTypeDescription();

        case EQUIPMENT:
            return v.getEquipment();

        case LOCATION:
            return v.getLocation();

        case MAP_KEY:
            return v.getMapKey();

        case KEY:
            return v.getKey();

        default:
            throw new IllegalArgumentException();
        }
    }

    public int getColumnCount() {
        return 11;
    }

    protected Class<?> getValueClass() {
        return gks.clark.inspections.model.Site.class;
    }
}
