/*
 * NOTICES
 * -------
 *
 * Copyright 2026 by Gatekeeper Systems All Rights Reserved.
 *
 * Unpublished Work -- Protected under the copyright laws of the United States.
 *
 * Restricted Rights Legend: Use, duplication or disclosure of the software
 * contained hereon is governed by the terms of a license agreement.  In
 * the absence of an agreement, use, duplication or disclosure by the United
 * States Government is subject to restrictions stated in subparagraph
 * (c)(1) of the Commercial Computer Software -- Restricted Rights clause
 * at FAR 52.227-9 or subparagraph (c)(1)(ii) of the Rights in Technical
 * Data and Computer Software clause at DFARS 252.227-7013, as applicable.
 *
 * Contractor/Manufacturer:
 *
 *     Gatekeeper Systems
 *     1010 E. Union St.
 *     Pasadena, CA 91106
 *
 *     Tel: (626) 449-3070 or (800) 424-3070
 *     Fax: (626) 440-1742
 *
 *     E-Mail: info@gatekeeper.com
 *     URL:    http://www.gatekeeper.com
 *
 * Generated by scaffold version 4.0.1-SNAPSHOT rb1df1f95d84beef5f7b22947b69311d59e90d0c6
 */
package gks.clark.inspections.model;


/*
 ==========================================================================
 AUTO GENERATED FILE! - Do not edit, as your changes will be overwritten
 ==========================================================================
*/
public class SiteIdentifier implements gks.util.dto.DataTransferObject {
    /*
     ==========================================================================
     Fields
     ==========================================================================
    */
    String assetType;
    String assetID;
    double lon;
    double lat;

    /*
     ==========================================================================
     Constructors
     ==========================================================================
    */
    public SiteIdentifier() {
    }

    /*
     ==========================================================================
     Getter and setters
     ==========================================================================
    */
    public void setAssetType(String assetType) {
        this.assetType = assetType;
    }

    public String getAssetType() {
        return assetType;
    }

    public void setAssetID(String assetID) {
        this.assetID = assetID;
    }

    public String getAssetID() {
        return assetID;
    }

    public void setLon(double lon) {
        this.lon = lon;
    }

    public double getLon() {
        return lon;
    }

    public void setLat(double lat) {
        this.lat = lat;
    }

    public double getLat() {
        return lat;
    }

    /*
    ==========================================================================
    Server Serializable object methods
    ==========================================================================
    */
    public void parseFromStream(gks.util.dto.DataTransferInputStream stream)
        throws gks.util.dto.DataTransferException {
        this.assetType = stream.read();
        this.assetID = stream.read();
        this.lon = stream.readd();
        this.lat = stream.readd();
    }

    public void serializeToStream(gks.util.dto.DataTransferOutputStream stream)
        throws gks.util.dto.DataTransferException {
        stream.write(this.assetType);
        stream.write(this.assetID);
        stream.write(this.lon);
        stream.write(this.lat);
    }
}
