/*
 * NOTICES
 * -------
 *
 * Copyright 2026 by Gatekeeper Systems All Rights Reserved.
 *
 * Unpublished Work -- Protected under the copyright laws of the United States.
 *
 * Restricted Rights Legend: Use, duplication or disclosure of the software
 * contained hereon is governed by the terms of a license agreement.  In
 * the absence of an agreement, use, duplication or disclosure by the United
 * States Government is subject to restrictions stated in subparagraph
 * (c)(1) of the Commercial Computer Software -- Restricted Rights clause
 * at FAR 52.227-9 or subparagraph (c)(1)(ii) of the Rights in Technical
 * Data and Computer Software clause at DFARS 252.227-7013, as applicable.
 *
 * Contractor/Manufacturer:
 *
 *     Gatekeeper Systems
 *     1010 E. Union St.
 *     Pasadena, CA 91106
 *
 *     Tel: (626) 449-3070 or (800) 424-3070
 *     Fax: (626) 440-1742
 *
 *     E-Mail: info@gatekeeper.com
 *     URL:    http://www.gatekeeper.com
 *
 * Generated by scaffold version 3.4.0
 */
package gks.clark.inspections.model;


/*
 ==========================================================================
 AUTO GENERATED FILE! - Do not edit, as your changes will be overwritten
 ==========================================================================
*/
public class SiteList implements gks.util.dto.DataTransferObject {
    /*
     ==========================================================================
     Fields
     ==========================================================================
    */
    java.util.Date scheduleDate;
    String name;
    int totalNr;
    int completeNr;
    java.util.Date completeDate;
    String planner;

    /*
     ==========================================================================
     Constructors
     ==========================================================================
    */
    public SiteList() {
    }

    /*
     ==========================================================================
     Getter and setters
     ==========================================================================
    */
    public void setScheduleDate(java.util.Date scheduleDate) {
        this.scheduleDate = scheduleDate;
    }

    public java.util.Date getScheduleDate() {
        return scheduleDate;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public int getTotalNr() {
        return totalNr;
    }

    public int getCompleteNr() {
        return completeNr;
    }

    public java.util.Date getCompleteDate() {
        return completeDate;
    }

    public String getPlanner() {
        return planner;
    }

    /*
    ==========================================================================
    Server Serializable object methods
    ==========================================================================
    */
    public void parseFromStream(gks.util.dto.DataTransferInputStream stream)
        throws gks.util.dto.DataTransferException {
        this.scheduleDate = stream.readDate();
        this.name = stream.read();
        this.totalNr = stream.readi();
        this.completeNr = stream.readi();
        this.completeDate = stream.readDate();
        this.planner = stream.read();
    }

    public void serializeToStream(gks.util.dto.DataTransferOutputStream stream)
        throws gks.util.dto.DataTransferException {
        stream.write(this.scheduleDate);
        stream.write(this.name);
        stream.write(this.totalNr);
        stream.write(this.completeNr);
        stream.write(this.completeDate);
        stream.write(this.planner);
    }
}
