/*
 * NOTICES
 * -------
 *
 * Copyright 2026 by Gatekeeper Systems All Rights Reserved.
 *
 * Unpublished Work -- Protected under the copyright laws of the United States.
 *
 * Restricted Rights Legend: Use, duplication or disclosure of the software
 * contained hereon is governed by the terms of a license agreement.  In
 * the absence of an agreement, use, duplication or disclosure by the United
 * States Government is subject to restrictions stated in subparagraph
 * (c)(1) of the Commercial Computer Software -- Restricted Rights clause
 * at FAR 52.227-9 or subparagraph (c)(1)(ii) of the Rights in Technical
 * Data and Computer Software clause at DFARS 252.227-7013, as applicable.
 *
 * Contractor/Manufacturer:
 *
 *     Gatekeeper Systems
 *     1010 E. Union St.
 *     Pasadena, CA 91106
 *
 *     Tel: (626) 449-3070 or (800) 424-3070
 *     Fax: (626) 440-1742
 *
 *     E-Mail: info@gatekeeper.com
 *     URL:    http://www.gatekeeper.com
 *
 * Generated by scaffold version 4.0.1-SNAPSHOT rb1df1f95d84beef5f7b22947b69311d59e90d0c6
 */
package gks.clark.inspections.model;


/*
 ==========================================================================
 AUTO GENERATED FILE! - Do not edit, as your changes will be overwritten
 ==========================================================================
*/
public class SiteList implements gks.util.dto.ServerTransferObject {
    /*
     ==========================================================================
     Fields
     ==========================================================================
    */
    gks.clark.inspections.model.Program program;
    String workOrder;
    gks.clark.inspections.model.Department department;
    gks.clark.inspections.model.Crew crew;
    gks.clark.inspections.model.SiteIdentifier[] sites;

    /*
     ==========================================================================
     Constructors
     ==========================================================================
    */
    public SiteList() {
    }

    /*
     ==========================================================================
     Getter and setters
     ==========================================================================
    */
    public void setProgram(gks.clark.inspections.model.Program program) {
        this.program = program;
    }

    public gks.clark.inspections.model.Program getProgram() {
        return program;
    }

    public void setWorkOrder(String workOrder) {
        this.workOrder = workOrder;
    }

    public String getWorkOrder() {
        return workOrder;
    }

    public void setDepartment(gks.clark.inspections.model.Department department) {
        this.department = department;
    }

    public gks.clark.inspections.model.Department getDepartment() {
        return department;
    }

    public void setCrew(gks.clark.inspections.model.Crew crew) {
        this.crew = crew;
    }

    public gks.clark.inspections.model.Crew getCrew() {
        return crew;
    }

    public void setSites(gks.clark.inspections.model.SiteIdentifier[] sites) {
        this.sites = sites;
    }

    public gks.clark.inspections.model.SiteIdentifier[] getSites() {
        return sites;
    }

    public String getKey() {
        return "";
    }

    /*
    ==========================================================================
    Server Serializable object methods
    ==========================================================================
    */
    public void parseFromStream(gks.util.dto.DataTransferInputStream stream)
        throws gks.util.dto.DataTransferException {
        this.program = stream.readCode(gks.clark.inspections.model.Program.class);
        this.workOrder = stream.read();
        this.department = stream.readCode(gks.clark.inspections.model.Department.class);
        this.crew = stream.readCode(gks.clark.inspections.model.Crew.class);

        Integer __sites_countObj = stream.readInteger();

        if (__sites_countObj != null) {
            int __sites_count = __sites_countObj.intValue();
            this.sites = new gks.clark.inspections.model.SiteIdentifier[__sites_count];

            for (int k = 0; k < __sites_count; ++k) {
                this.sites[k] = new gks.clark.inspections.model.SiteIdentifier();
                this.sites[k].parseFromStream(stream);
            }
        } else {
            this.sites = null;
        }
    }

    public void serializeToStream(gks.util.dto.DataTransferOutputStream stream)
        throws gks.util.dto.DataTransferException {
        stream.write(this.program);
        stream.write(this.workOrder);
        stream.write(this.department);
        stream.write(this.crew);

        if (this.sites != null) {
            stream.write(this.sites.length);

            for (int k = 0; k < this.sites.length; ++k) {
                this.sites[k].serializeToStream(stream);
            }
        } else {
            stream.writeNull();
        }
    }

    public void serializeModifiableToStream(
        gks.util.dto.DataTransferOutputStream stream)
        throws gks.util.dto.DataTransferException {
        stream.write(this.program);
        stream.write(this.workOrder);
        stream.write(this.department);
        stream.write(this.crew);

        if (this.sites != null) {
            stream.write(this.sites.length);

            for (int k = 0; k < this.sites.length; ++k) {
                this.sites[k].serializeToStream(stream);
            }
        } else {
            stream.writeNull();
        }
    }
}
