/*
 * NOTICES
 * -------
 *
 * Copyright 2026 by Gatekeeper Systems All Rights Reserved.
 *
 * Unpublished Work -- Protected under the copyright laws of the United States.
 *
 * Restricted Rights Legend: Use, duplication or disclosure of the software
 * contained hereon is governed by the terms of a license agreement.  In
 * the absence of an agreement, use, duplication or disclosure by the United
 * States Government is subject to restrictions stated in subparagraph
 * (c)(1) of the Commercial Computer Software -- Restricted Rights clause
 * at FAR 52.227-9 or subparagraph (c)(1)(ii) of the Rights in Technical
 * Data and Computer Software clause at DFARS 252.227-7013, as applicable.
 *
 * Contractor/Manufacturer:
 *
 *     Gatekeeper Systems
 *     1010 E. Union St.
 *     Pasadena, CA 91106
 *
 *     Tel: (626) 449-3070 or (800) 424-3070
 *     Fax: (626) 440-1742
 *
 *     E-Mail: info@gatekeeper.com
 *     URL:    http://www.gatekeeper.com
 *
 * Generated by scaffold version 4.0.1-SNAPSHOT rb1df1f95d84beef5f7b22947b69311d59e90d0c6
 */
package gks.clark.inspections.model;


/*
 ==========================================================================
 AUTO GENERATED FILE! - Do not edit, as your changes will be overwritten
 ==========================================================================
*/
public class Site implements gks.util.dto.ServerTransferObject,
    gks.util.Mappable {
    /*
     ==========================================================================
     Fields
     ==========================================================================
    */
    String assetSource;
    String assetID;
    Double minX;
    Double minY;
    Double maxX;
    Double maxY;
    String typeDescription;
    String equipment;
    String location;

    /*
     ==========================================================================
     Constructors
     ==========================================================================
    */
    public Site() {
    }

    /*
    ==========================================================================
    Code includes
    ==========================================================================
    */
    public gks.util.BoundingBox getExtent(gks.util.BoundingBox scratchBox) {
        return gks.map.MapControl.getExtent(minX, minY, maxX, maxY, scratchBox);
    }

    public boolean isMappable() {
        return gks.map.MapControl.isMappable(minX, minY, maxX, maxY, getMapKey());
    }

    /*
     ==========================================================================
     Getter and setters
     ==========================================================================
    */
    public String getAssetSource() {
        return assetSource;
    }

    public String getAssetID() {
        return assetID;
    }

    public Double getMinX() {
        return minX;
    }

    public Double getMinY() {
        return minY;
    }

    public Double getMaxX() {
        return maxX;
    }

    public Double getMaxY() {
        return maxY;
    }

    public String getTypeDescription() {
        return typeDescription;
    }

    public String getEquipment() {
        return equipment;
    }

    public String getLocation() {
        return location;
    }

    public String getMapKey() {
        return assetSource + ":" + assetID;
    }

    public String getKey() {
        return assetSource + ":" + assetID;
    }

    /*
    ==========================================================================
    Server Serializable object methods
    ==========================================================================
    */
    public void parseFromStream(gks.util.dto.DataTransferInputStream stream)
        throws gks.util.dto.DataTransferException {
        this.assetSource = stream.read();
        this.assetID = stream.read();
        this.minX = stream.readDouble();
        this.minY = stream.readDouble();
        this.maxX = stream.readDouble();
        this.maxY = stream.readDouble();
        this.typeDescription = stream.read();
        this.equipment = stream.read();
        this.location = stream.read();
    }

    public void serializeToStream(gks.util.dto.DataTransferOutputStream stream)
        throws gks.util.dto.DataTransferException {
        stream.write(this.assetSource);
        stream.write(this.assetID);
        stream.write(this.minX);
        stream.write(this.minY);
        stream.write(this.maxX);
        stream.write(this.maxY);
        stream.write(this.typeDescription);
        stream.write(this.equipment);
        stream.write(this.location);
    }

    public void serializeModifiableToStream(
        gks.util.dto.DataTransferOutputStream stream)
        throws gks.util.dto.DataTransferException {
        stream.write(this.assetSource);
        stream.write(this.assetID);
    }

    /**
             * Factory method for creating an ArrayTableModel which will
             * serve this class. Table created is of class gks.clark.inspections.model.SiteTableModel
             *
             * @see gks.clark.inspections.model.SiteTableModel
             */
    public static gks.ui.table.ArrayTableModel createTableModel() {
        return new gks.clark.inspections.model.SiteTableModel();
    }
}
