/*
 * NOTICES
 * -------
 *
 * Copyright 2026 by Gatekeeper Systems All Rights Reserved.
 *
 * Unpublished Work -- Protected under the copyright laws of the United States.
 *
 * Restricted Rights Legend: Use, duplication or disclosure of the software
 * contained hereon is governed by the terms of a license agreement.  In
 * the absence of an agreement, use, duplication or disclosure by the United
 * States Government is subject to restrictions stated in subparagraph
 * (c)(1) of the Commercial Computer Software -- Restricted Rights clause
 * at FAR 52.227-9 or subparagraph (c)(1)(ii) of the Rights in Technical
 * Data and Computer Software clause at DFARS 252.227-7013, as applicable.
 *
 * Contractor/Manufacturer:
 *
 *     Gatekeeper Systems
 *     1010 E. Union St.
 *     Pasadena, CA 91106
 *
 *     Tel: (626) 449-3070 or (800) 424-3070
 *     Fax: (626) 440-1742
 *
 *     E-Mail: info@gatekeeper.com
 *     URL:    http://www.gatekeeper.com
 *
 * Generated by scaffold version 3.4.0
 */
package gks.clark.inspections.model;


/*
 ==========================================================================
 AUTO GENERATED FILE! - Do not edit, as your changes will be overwritten
 ==========================================================================
*/
public class SiteList implements gks.util.dto.ServerTransferObject {
    /*
     ==========================================================================
     Fields
     ==========================================================================
    */
    String workOrder;
    gks.clark.inspections.model.Site[] sites;

    /*
     ==========================================================================
     Constructors
     ==========================================================================
    */
    public SiteList() {
    }

    /*
     ==========================================================================
     Getter and setters
     ==========================================================================
    */
    public void setWorkOrder(String workOrder) {
        this.workOrder = workOrder;
    }

    public String getWorkOrder() {
        return workOrder;
    }

    public void setSites(gks.clark.inspections.model.Site[] sites) {
        this.sites = sites;
    }

    public gks.clark.inspections.model.Site[] getSites() {
        return sites;
    }

    public String getKey() {
        return "";
    }

    /*
    ==========================================================================
    Server Serializable object methods
    ==========================================================================
    */
    public void parseFromStream(gks.util.dto.DataTransferInputStream stream)
        throws gks.util.dto.DataTransferException {
        this.workOrder = stream.read();

        Integer __sites_countObj = stream.readInteger();

        if (__sites_countObj != null) {
            int __sites_count = __sites_countObj.intValue();
            this.sites = new gks.clark.inspections.model.Site[__sites_count];

            for (int k = 0; k < __sites_count; ++k) {
                this.sites[k] = new gks.clark.inspections.model.Site();
                this.sites[k].parseFromStream(stream);
            }
        } else {
            this.sites = null;
        }
    }

    public void serializeToStream(gks.util.dto.DataTransferOutputStream stream)
        throws gks.util.dto.DataTransferException {
        stream.write(this.workOrder);

        if (this.sites != null) {
            stream.write(this.sites.length);

            for (int k = 0; k < this.sites.length; ++k) {
                this.sites[k].serializeToStream(stream);
            }
        } else {
            stream.writeNull();
        }
    }

    public void serializeModifiableToStream(
        gks.util.dto.DataTransferOutputStream stream)
        throws gks.util.dto.DataTransferException {
        stream.write(this.workOrder);

        if (this.sites != null) {
            stream.write(this.sites.length);

            for (int k = 0; k < this.sites.length; ++k) {
                this.sites[k].serializeModifiableToStream(stream);
            }
        } else {
            stream.writeNull();
        }
    }
}
