/*
 * NOTICES
 * -------
 *
 * Copyright 2026 by Gatekeeper Systems All Rights Reserved.
 *
 * Unpublished Work -- Protected under the copyright laws of the United States.
 *
 * Restricted Rights Legend: Use, duplication or disclosure of the software
 * contained hereon is governed by the terms of a license agreement.  In
 * the absence of an agreement, use, duplication or disclosure by the United
 * States Government is subject to restrictions stated in subparagraph
 * (c)(1) of the Commercial Computer Software -- Restricted Rights clause
 * at FAR 52.227-9 or subparagraph (c)(1)(ii) of the Rights in Technical
 * Data and Computer Software clause at DFARS 252.227-7013, as applicable.
 *
 * Contractor/Manufacturer:
 *
 *     Gatekeeper Systems
 *     1010 E. Union St.
 *     Pasadena, CA 91106
 *
 *     Tel: (626) 449-3070 or (800) 424-3070
 *     Fax: (626) 440-1742
 *
 *     E-Mail: info@gatekeeper.com
 *     URL:    http://www.gatekeeper.com
 *
 * Generated by scaffold version 3.4.0
 */
package gks.clark.inspections.model;


/*
 ==========================================================================
 AUTO GENERATED FILE! - Do not edit, as your changes will be overwritten
 ==========================================================================
*/
public class SiteFilter extends gks.field.list.FieldListFilter {
    private static final long serialVersionUID = 1617871015443L;

    /*
     ==========================================================================
     Fields
     ==========================================================================
    */
    String circuit;

    /*
     ==========================================================================
     Constructors
     ==========================================================================
    */
    public SiteFilter() {
    }

    /*
    ==========================================================================
    Code includes
    ==========================================================================
    */
    public String urlQueryString() {
        gks.util.QueryBuilder buffer = new gks.util.QueryBuilder();
        buffer.append("CIRCUIT", getCircuit());

        return buffer.toString();
    }

    public String displayString() {
        StringBuffer buffer = new StringBuffer();
        int count = 0;

        if (getCircuit() != null) {
            if (count > 0) {
                buffer.append('\n');
            }

            buffer.append("Circuit");
            buffer.append(": ");

            // String
            buffer.append(getCircuit());
            count++;
        }

        return buffer.toString();
    }

    /*
     ==========================================================================
     Getter and setters
     ==========================================================================
    */
    public void setCircuit(String circuit) {
        this.circuit = circuit;
    }

    public String getCircuit() {
        return circuit;
    }

    public Class getItemType() {
        return gks.clark.inspections.model.Site.class;
    }

    public String getFilterName() {
        StringBuffer buffer = new StringBuffer();

        if (!gks.util.Utils.isEmpty(getCircuit())) {
            buffer.append(getCircuit());
        }

        return buffer.toString();
    }

    /*
    ==========================================================================
    Server Serializable object methods
    ==========================================================================
    */
    public void parseFromStream(gks.util.dto.DataTransferInputStream stream)
        throws gks.util.dto.DataTransferException {
        super.parseFromStream(stream);

        this.circuit = stream.read();
    }

    public void serializeToStream(gks.util.dto.DataTransferOutputStream stream)
        throws gks.util.dto.DataTransferException {
        super.serializeToStream(stream);

        stream.write(this.circuit);
    }

    /*
    ==========================================================================
    Externalizable implementation
    ==========================================================================
    */
    public void readExternal(java.io.ObjectInput in)
        throws java.io.IOException, ClassNotFoundException {
        try {
            parseFromStream(new gks.util.dto.BinaryTransferInputStream(in));
        } catch (gks.util.dto.DataTransferException e) {
            throw new java.io.IOException("Failure during readExternal()", e);
        }
    }

    public void writeExternal(java.io.ObjectOutput out)
        throws java.io.IOException {
        try {
            serializeToStream(new gks.util.dto.BinaryTransferOutputStream(out));
        } catch (gks.util.dto.DataTransferException e) {
            throw new java.io.IOException("Failure during writeExternal()", e);
        }
    }
}
