/*
 * NOTICES
 * -------
 *
 * Copyright 2026 by Gatekeeper Systems All Rights Reserved.
 *
 * Unpublished Work -- Protected under the copyright laws of the United States.
 *
 * Restricted Rights Legend: Use, duplication or disclosure of the software
 * contained hereon is governed by the terms of a license agreement.  In
 * the absence of an agreement, use, duplication or disclosure by the United
 * States Government is subject to restrictions stated in subparagraph
 * (c)(1) of the Commercial Computer Software -- Restricted Rights clause
 * at FAR 52.227-9 or subparagraph (c)(1)(ii) of the Rights in Technical
 * Data and Computer Software clause at DFARS 252.227-7013, as applicable.
 *
 * Contractor/Manufacturer:
 *
 *     Gatekeeper Systems
 *     1010 E. Union St.
 *     Pasadena, CA 91106
 *
 *     Tel: (626) 449-3070 or (800) 424-3070
 *     Fax: (626) 440-1742
 *
 *     E-Mail: info@gatekeeper.com
 *     URL:    http://www.gatekeeper.com
 *
 * Generated by scaffold version 3.4.0
 */
package gks.clark.inspections.model;


/**
 * TableModel implementation for {@link gks.clark.inspections.model.SiteList}
 *
 * AUTO GENERATED FILE! - Do not edit, as your changes will be overwritten
 */
public class SiteListTableModel extends gks.ui.table.ArrayTableModel {
    private static final long serialVersionUID = 1L;
    public static final int ITEM_TYPE = 0;
    public static final int DATA = 1;
    public static final int EDITION = 2;
    public static final int MAX_STOP = 3;
    public static final int FILTER = 4;
    public static final int LOCKVERSION = 5;
    public static final int VALID = 6;
    public static final int SIZE = 7;
    public static final int MODIFIABLE_DATA = 8;
    public static final int ID = 9;
    public static final int FILTER_TYPE = 10;
    public static final int PERSISTENT = 11;
    public static final int CLASS = 12;
    public static final int MIN_STOP = 13;
    public static final int KEY = 14;
    public static final int CHANGED = 15;
    public static final int SCHEDULE_DATE = 16;
    public static final int NAME = 17;
    public static final int TOTAL_NR = 18;
    public static final int COMPLETE_NR = 19;
    public static final int COMPLETE_DATE = 20;
    public static final int PLANNER = 21;
    public static final int DISPLAY_NAME = 22;
    private static final String[] COLUMN_NAMES = {
            "itemType", "data", "edition", "maxStop", "filter", "lockversion",
            "valid", "size", "modifiableData", "ID", "filterType", "persistent",
            "class", "minStop", "key", "changed", "scheduleDate", "name",
            "totalNr", "completeNr", "completeDate", "planner", "displayName",
        };

    public String getColumnName(int column) {
        if (column < 0) {
            return super.getColumnName(column);
        }

        return COLUMN_NAMES[column];
    }

    public Class<?> getColumnClass(int column) {
        if (column < 0) {
            return super.getColumnClass(column);
        }

        switch (column) {
        case ITEM_TYPE:
        case FILTER_TYPE:
        case CLASS:
            return Class.class;

        case SCHEDULE_DATE:
        case COMPLETE_DATE:
            return java.util.Date.class;

        case FILTER:
            return gks.field.list.FieldListFilter.class;

        case MAX_STOP:
        case MIN_STOP:
            return Integer.class;

        case DATA:
        case MODIFIABLE_DATA:
            return java.util.List.class;

        case VALID:
        case PERSISTENT:
        case CHANGED:
            return Boolean.class;

        case EDITION:
        case LOCKVERSION:
        case SIZE:
        case TOTAL_NR:
        case COMPLETE_NR:
            return Integer.class;

        case ID:
            return Long.class;

        default:
            return String.class;
        }
    }

    public Object getValueAt(Object value, int column) {
        gks.clark.inspections.model.SiteList v = (gks.clark.inspections.model.SiteList) value;

        switch (column) {
        case ITEM_TYPE:
            return v.getItemType();

        case DATA:
            return java.util.Arrays.asList(v.getData());

        case EDITION:
            return new Integer(v.getEdition());

        case MAX_STOP:
            return v.getMaxStop();

        case FILTER:
            return v.getFilter();

        case LOCKVERSION:
            return new Integer(v.getLockversion());

        case VALID:
            return Boolean.valueOf(v.isValid());

        case SIZE:
            return new Integer(v.getSize());

        case MODIFIABLE_DATA:
            return java.util.Arrays.asList(v.getModifiableData());

        case ID:
            return new Long(v.getID());

        case FILTER_TYPE:
            return v.getFilterType();

        case PERSISTENT:
            return Boolean.valueOf(v.isPersistent());

        case CLASS:
            return v.getClass();

        case MIN_STOP:
            return v.getMinStop();

        case KEY:
            return v.getKey();

        case CHANGED:
            return Boolean.valueOf(v.isChanged());

        case SCHEDULE_DATE:
            return v.getScheduleDate();

        case NAME:
            return v.getName();

        case TOTAL_NR:
            return new Integer(v.getTotalNr());

        case COMPLETE_NR:
            return new Integer(v.getCompleteNr());

        case COMPLETE_DATE:
            return v.getCompleteDate();

        case PLANNER:
            return v.getPlanner();

        case DISPLAY_NAME:
            return v.getDisplayName();

        default:
            throw new IllegalArgumentException();
        }
    }

    public int getColumnCount() {
        return 23;
    }

    protected Class<?> getValueClass() {
        return gks.clark.inspections.model.SiteList.class;
    }
}
