/*
 * NOTICES
 * -------
 *
 * Copyright 2026 by Gatekeeper Systems All Rights Reserved.
 *
 * Unpublished Work -- Protected under the copyright laws of the United States.
 *
 * Restricted Rights Legend: Use, duplication or disclosure of the software
 * contained hereon is governed by the terms of a license agreement.  In
 * the absence of an agreement, use, duplication or disclosure by the United
 * States Government is subject to restrictions stated in subparagraph
 * (c)(1) of the Commercial Computer Software -- Restricted Rights clause
 * at FAR 52.227-9 or subparagraph (c)(1)(ii) of the Rights in Technical
 * Data and Computer Software clause at DFARS 252.227-7013, as applicable.
 *
 * Contractor/Manufacturer:
 *
 *     Gatekeeper Systems
 *     1010 E. Union St.
 *     Pasadena, CA 91106
 *
 *     Tel: (626) 449-3070 or (800) 424-3070
 *     Fax: (626) 440-1742
 *
 *     E-Mail: info@gatekeeper.com
 *     URL:    http://www.gatekeeper.com
 *
 * Generated by scaffold version 4.0.1-SNAPSHOT rb1df1f95d84beef5f7b22947b69311d59e90d0c6
 */
package gks.clark.inspections.model;


/*
 ==========================================================================
 AUTO GENERATED FILE! - Do not edit, as your changes will be overwritten
 ==========================================================================
*/
public class WorkOrder implements gks.util.dto.ServerTransferObject,
    gks.util.Mappable {
    /*
     ==========================================================================
     Fields
     ==========================================================================
    */
    String key;
    String orderType;
    Double x;
    Double y;
    String orderSubKey;
    String orderNumber;
    String orderSubType;
    String entryTs;
    String customerName;
    String resPhone;
    String busPhone;
    String callFirst;
    String serviceAccount;
    String serviceAddress;
    String serviceCity;
    String serviceZip;
    String request;
    String reason;
    String orderDesc;
    String workLocation;
    String workLocationDescription;
    String creationUser;
    String listId;
    Integer listCompleted;
    Integer listTotal;
    String crew;

    /*
     ==========================================================================
     Constructors
     ==========================================================================
    */
    public WorkOrder() {
    }

    /*
    ==========================================================================
    Code includes
    ==========================================================================
    */
    public gks.util.BoundingBox getExtent(gks.util.BoundingBox scratchBox) {
        return gks.map.MapControl.getExtent(x, y, scratchBox);
    }

    public boolean isMappable() {
        return ((x != null) && (y != null))
        ? gks.map.MapControl.isMappable(x, y, getMapKey()) : false;
    }

    /*
     ==========================================================================
     Getter and setters
     ==========================================================================
    */
    public String getKey() {
        return key;
    }

    public String getOrderType() {
        return orderType;
    }

    public Double getX() {
        return x;
    }

    public Double getY() {
        return y;
    }

    public String getOrderSubKey() {
        return orderSubKey;
    }

    public String getOrderNumber() {
        return orderNumber;
    }

    public String getOrderSubType() {
        return orderSubType;
    }

    public String getEntryTs() {
        return entryTs;
    }

    public String getCustomerName() {
        return customerName;
    }

    public String getResPhone() {
        return resPhone;
    }

    public String getBusPhone() {
        return busPhone;
    }

    public String getCallFirst() {
        return callFirst;
    }

    public String getServiceAccount() {
        return serviceAccount;
    }

    public String getServiceAddress() {
        return serviceAddress;
    }

    public String getServiceCity() {
        return serviceCity;
    }

    public String getServiceZip() {
        return serviceZip;
    }

    public String getRequest() {
        return request;
    }

    public String getReason() {
        return reason;
    }

    public String getOrderDesc() {
        return orderDesc;
    }

    public String getWorkLocation() {
        return workLocation;
    }

    public String getWorkLocationDescription() {
        return workLocationDescription;
    }

    public String getCreationUser() {
        return creationUser;
    }

    public String getListId() {
        return listId;
    }

    public Integer getListCompleted() {
        return listCompleted;
    }

    public Integer getListTotal() {
        return listTotal;
    }

    public String getCrew() {
        return crew;
    }

    public String getStatus() {
        if (gks.util.Utils.isEmpty(listId)) {
            return null;
        }

        return ((listCompleted != null) && (listTotal != null) &&
        listCompleted.equals(listTotal)) ? "C" : "I";
    }

    public String getMapKey() {
        return key;
    }

    public String getServiceAddressComplete() {
        boolean hasAddress = gks.util.Utils.isNotEmpty(serviceAddress);
        boolean hasCity = gks.util.Utils.isNotEmpty(serviceCity);
        boolean hasZip = gks.util.Utils.isNotEmpty(serviceZip);
        java.util.ArrayList<String> lines = new java.util.ArrayList<String>(2);

        // line 1
        if (hasAddress) {
            lines.add(serviceAddress);
        }

        // line 2
        if (hasCity && hasZip) {
            lines.add(serviceCity + ", " + serviceZip);
        } else if (hasCity) {
            lines.add(serviceCity);
        } else if (hasZip) {
            lines.add(serviceZip);
        }

        return gks.util.Utils.join("\n", lines);
    }

    /*
    ==========================================================================
    Server Serializable object methods
    ==========================================================================
    */
    public void parseFromStream(gks.util.dto.DataTransferInputStream stream)
        throws gks.util.dto.DataTransferException {
        this.key = stream.read();
        this.orderType = stream.read();
        this.x = stream.readDouble();
        this.y = stream.readDouble();
        this.orderSubKey = stream.read();
        this.orderNumber = stream.read();
        this.orderSubType = stream.read();
        this.entryTs = stream.read();
        this.customerName = stream.read();
        this.resPhone = stream.read();
        this.busPhone = stream.read();
        this.callFirst = stream.read();
        this.serviceAccount = stream.read();
        this.serviceAddress = stream.read();
        this.serviceCity = stream.read();
        this.serviceZip = stream.read();
        this.request = stream.read();
        this.reason = stream.read();
        this.orderDesc = stream.read();
        this.workLocation = stream.read();
        this.workLocationDescription = stream.read();
        this.creationUser = stream.read();
        this.listId = stream.read();
        this.listCompleted = stream.readInteger();
        this.listTotal = stream.readInteger();
        this.crew = stream.read();
    }

    public void serializeToStream(gks.util.dto.DataTransferOutputStream stream)
        throws gks.util.dto.DataTransferException {
        stream.write(this.key);
        stream.write(this.orderType);
        stream.write(this.x);
        stream.write(this.y);
        stream.write(this.orderSubKey);
        stream.write(this.orderNumber);
        stream.write(this.orderSubType);
        stream.write(this.entryTs);
        stream.write(this.customerName);
        stream.write(this.resPhone);
        stream.write(this.busPhone);
        stream.write(this.callFirst);
        stream.write(this.serviceAccount);
        stream.write(this.serviceAddress);
        stream.write(this.serviceCity);
        stream.write(this.serviceZip);
        stream.write(this.request);
        stream.write(this.reason);
        stream.write(this.orderDesc);
        stream.write(this.workLocation);
        stream.write(this.workLocationDescription);
        stream.write(this.creationUser);
        stream.write(this.listId);
        stream.write(this.listCompleted);
        stream.write(this.listTotal);
        stream.write(this.crew);
    }

    public void serializeModifiableToStream(
        gks.util.dto.DataTransferOutputStream stream)
        throws gks.util.dto.DataTransferException {
        stream.write(this.key);
    }

    /**
             * Factory method for creating an ArrayTableModel which will
             * serve this class. Table created is of class gks.clark.inspections.model.WorkOrderTableModel
             *
             * @see gks.clark.inspections.model.WorkOrderTableModel
             */
    public static gks.ui.table.ArrayTableModel createTableModel() {
        return new gks.clark.inspections.model.WorkOrderTableModel();
    }
}
