/*
 * NOTICES
 * -------
 *
 * Copyright 2026 by Gatekeeper Systems All Rights Reserved.
 *
 * Unpublished Work -- Protected under the copyright laws of the United States.
 *
 * Restricted Rights Legend: Use, duplication or disclosure of the software
 * contained hereon is governed by the terms of a license agreement.  In
 * the absence of an agreement, use, duplication or disclosure by the United
 * States Government is subject to restrictions stated in subparagraph
 * (c)(1) of the Commercial Computer Software -- Restricted Rights clause
 * at FAR 52.227-9 or subparagraph (c)(1)(ii) of the Rights in Technical
 * Data and Computer Software clause at DFARS 252.227-7013, as applicable.
 *
 * Contractor/Manufacturer:
 *
 *     Gatekeeper Systems
 *     1010 E. Union St.
 *     Pasadena, CA 91106
 *
 *     Tel: (626) 449-3070 or (800) 424-3070
 *     Fax: (626) 440-1742
 *
 *     E-Mail: info@gatekeeper.com
 *     URL:    http://www.gatekeeper.com
 *
 * Generated by scaffold version 4.0.1-SNAPSHOT rb1df1f95d84beef5f7b22947b69311d59e90d0c6
 */
package gks.clark.inspections.model;


/**
 * TableModel implementation for {@link gks.clark.inspections.model.WorkOrder}
 *
 * AUTO GENERATED FILE! - Do not edit, as your changes will be overwritten
 */
public class WorkOrderTableModel extends gks.ui.table.ArrayTableModel {
    private static final long serialVersionUID = 1L;
    public static final int KEY = 0;
    public static final int ORDER_TYPE = 1;
    public static final int X = 2;
    public static final int Y = 3;
    public static final int ORDER_SUB_KEY = 4;
    public static final int ORDER_NUMBER = 5;
    public static final int ORDER_SUB_TYPE = 6;
    public static final int ENTRY_TS = 7;
    public static final int CUSTOMER_NAME = 8;
    public static final int RES_PHONE = 9;
    public static final int BUS_PHONE = 10;
    public static final int CALL_FIRST = 11;
    public static final int SERVICE_ACCOUNT = 12;
    public static final int SERVICE_ADDRESS = 13;
    public static final int SERVICE_CITY = 14;
    public static final int SERVICE_ZIP = 15;
    public static final int REQUEST = 16;
    public static final int REASON = 17;
    public static final int ORDER_DESC = 18;
    public static final int WORK_LOCATION = 19;
    public static final int WORK_LOCATION_DESCRIPTION = 20;
    public static final int CREATION_USER = 21;
    public static final int LIST_ID = 22;
    public static final int LIST_COMPLETED = 23;
    public static final int LIST_TOTAL = 24;
    public static final int CREW = 25;
    public static final int STATUS = 26;
    public static final int MAP_KEY = 27;
    public static final int SERVICE_ADDRESS_COMPLETE = 28;
    private static final String[] COLUMN_NAMES = {
            "key", "orderType", "x", "y", "orderSubKey", "orderNumber",
            "orderSubType", "entryTs", "customerName", "resPhone", "busPhone",
            "callFirst", "serviceAccount", "serviceAddress", "serviceCity",
            "serviceZip", "request", "reason", "orderDesc", "workLocation",
            "workLocationDescription", "creationUser", "listId", "listCompleted",
            "listTotal", "crew", "status", "mapKey", "serviceAddressComplete",
        };

    public String getColumnName(int column) {
        if (column < 0) {
            return super.getColumnName(column);
        }

        return COLUMN_NAMES[column];
    }

    public Class<?> getColumnClass(int column) {
        if (column < 0) {
            return super.getColumnClass(column);
        }

        switch (column) {
        case X:
        case Y:
            return Double.class;

        case LIST_COMPLETED:
        case LIST_TOTAL:
            return Integer.class;

        default:
            return String.class;
        }
    }

    public Object getValueAt(Object value, int column) {
        gks.clark.inspections.model.WorkOrder v = (gks.clark.inspections.model.WorkOrder) value;

        switch (column) {
        case KEY:
            return v.getKey();

        case ORDER_TYPE:
            return v.getOrderType();

        case X:
            return v.getX();

        case Y:
            return v.getY();

        case ORDER_SUB_KEY:
            return v.getOrderSubKey();

        case ORDER_NUMBER:
            return v.getOrderNumber();

        case ORDER_SUB_TYPE:
            return v.getOrderSubType();

        case ENTRY_TS:
            return v.getEntryTs();

        case CUSTOMER_NAME:
            return v.getCustomerName();

        case RES_PHONE:
            return v.getResPhone();

        case BUS_PHONE:
            return v.getBusPhone();

        case CALL_FIRST:
            return v.getCallFirst();

        case SERVICE_ACCOUNT:
            return v.getServiceAccount();

        case SERVICE_ADDRESS:
            return v.getServiceAddress();

        case SERVICE_CITY:
            return v.getServiceCity();

        case SERVICE_ZIP:
            return v.getServiceZip();

        case REQUEST:
            return v.getRequest();

        case REASON:
            return v.getReason();

        case ORDER_DESC:
            return v.getOrderDesc();

        case WORK_LOCATION:
            return v.getWorkLocation();

        case WORK_LOCATION_DESCRIPTION:
            return v.getWorkLocationDescription();

        case CREATION_USER:
            return v.getCreationUser();

        case LIST_ID:
            return v.getListId();

        case LIST_COMPLETED:
            return v.getListCompleted();

        case LIST_TOTAL:
            return v.getListTotal();

        case CREW:
            return v.getCrew();

        case STATUS:
            return v.getStatus();

        case MAP_KEY:
            return v.getMapKey();

        case SERVICE_ADDRESS_COMPLETE:
            return v.getServiceAddressComplete();

        default:
            throw new IllegalArgumentException();
        }
    }

    public int getColumnCount() {
        return 29;
    }

    protected Class<?> getValueClass() {
        return gks.clark.inspections.model.WorkOrder.class;
    }
}
