managers = site, list

manager.site = gks.clark.inspections.model.Site
manager.site.type = gks.clark.inspections.model.Site
manager.site.readURL = /scripts/inspections/read_site
manager.site.persistentCacheEnabled = false
manager.site.lockversionHash = true


manager.list = gks.field.list.FieldList
manager.list.type = gks.clark.inspections.model.SiteList
manager.list.createURL = /scripts/inspections/create_site_list
manager.list.readURL = /scripts/inspections/read_site_list
manager.list.writeURL = /scripts/inspections/update_site_list
manager.list.deleteURL = /scripts/inspections/delete_site_list
manager.list.persistentCacheEnabled = false

buildVersion = 2026-04-06
