title = Inspections
tableConfigPath = gks/clark/inspections/tableColumns.xml
tableColumnSet = gks.clark.inspections.model.Site
tableModelClass = gks.clark.inspections.model.SiteTableModel
actionConfigPath = gks/clark/inspections/action.xml
tableOpenAction = open
#mapDoubleClickAction = open
dataClass=http:/scripts/inspections/read_codes,data:trace/data.js
#dataClass=http:/scripts/inspections/read_codes
mapLayer = physical:Work Order