create table dbo.WM_INSPECTION (
ID int identity,
LIST_ID INTEGER NOT NULL,
ASSET_ID INTEGER NOT NULL,
X float,
Y float,
COMPLETION_STATUS varchar(1),
COMMENT varchar(2000),
ISSUE_PRIORITY varchar(1),
COMPLETION_DATE datetime,
COMPLETION_USER varchar(100)
);
